use std::collections::HashMap;

use crate::types::{KeywordGroup, KeywordBlurb, BlurbVec};

lazy_static! {
    pub static ref KEYWORDS_GROUP_MAP: HashMap<&'static str, KeywordGroup<'static>> = {
        let m = hashmap! {
        "frontend" => KeywordGroup{ score: 3, trigger_tokens: vec!["react", "reactjs", "angular", "angularjs", "vue"]},
        "favourite_languages" => KeywordGroup {score: 5, trigger_tokens: vec!["rust", "typescript"]},
        "dotnet" => KeywordGroup{ score: 4, trigger_tokens: vec!["c#", ".net"]},
        "rust" => KeywordGroup{ score: 5, trigger_tokens: vec!["rust"]},
        "golang" => KeywordGroup{ score: 2, trigger_tokens: vec!["golang"]},
        "python" => KeywordGroup{ score: 5, trigger_tokens: vec!["python", "flask"]}
        };
        m
    };
}

// TODO: Move this to yaml
lazy_static! {
    pub static ref BLURBS: BlurbVec<'static> = {
        let mut v = Vec::new();
        v.push(
            KeywordBlurb{
                name: "intro",
                precendence: 255,
                trigger_tokens: vec![],
                long_description: "Hey I'm Ash,\
                \nI'm a new grad from UBC with a years experience working as a software engineer at Ravelin.\
                \nMy resume already outlines my general technical accomplishments at the places I've worked \
                but I would like to expand on the projects I've worked on that make a great fit at {COMPANY}!"
            });
        v.push(
            KeywordBlurb{
                name: "typescript",
                precendence: 9,
                trigger_tokens: vec!["typescript"],
                long_description: "TypeScript has made developing in the JavaScript ecosystem a pleasure"
            }
        );
        v.push(
            KeywordBlurb{
                name: "react",
                precendence: 9,
                trigger_tokens: vec!["react", "reactjs", "typescript"],
                long_description:  "I built a card matching game using React+TypeScript to help my grandma \
                learn the sounds of the English alphabet in fun way. \
                \nSource: https://arashout.github.io/alphabet-match/"
            }
        );
        v.push(
            KeywordBlurb{
                name: "sdet",
                precendence: 9,
                trigger_tokens: vec!["selenium","cypress", "phantamjs", "scraping"],
                long_description: "I'm particularly obsessed with automation, so much so that I built a robot to apply to jobs for me using \
                Selenium. Thus I have a significant amount of experience automating web browsers which will come in handy for automated testing."
            }
        );
        v.push(
            KeywordBlurb{
                name: "rust",
                precendence: 9,
                trigger_tokens: vec!["rust"],
                long_description: "I've recently gotten interested in Rust and regularly attend a Rust meet-up in Vancouver.
                In fact this message was generated by a small Rust console application!"
            }
        );
        v.push(
            KeywordBlurb{
                name: "vis",
                precendence: 9,
                trigger_tokens: vec!["visualization", "graph", "algorithms"],
                long_description: "Built efficient and useful graph visualization for the Ravelin connect product using D3.js. 
                This involved writing some graph traversal and nearest neighbor search algorithms."
            }
        );
        v.push(
            KeywordBlurb{
                name: "outro",
                precendence: 10,
                trigger_tokens: vec![],
                long_description: "This seems like an incredible opportunity so please do not hesitate to arrange an interview or ask any questions!"
            }
        );
        v
    };
}

